<?php

namespace ContainerZzadlXp;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConsultatiiRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\ConsultatiiRepository' shared autowired service.
     *
     * @return \App\Repository\ConsultatiiRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\ConsultatiiRepository'] = new \App\Repository\ConsultatiiRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
