<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZzadlXp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZzadlXp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZzadlXp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZzadlXp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZzadlXp\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZzadlXp',
    'container.build_id' => '74c617cc',
    'container.build_time' => 1749137976,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZzadlXp');
